// convert-tokens.js
import { readdir, readFile, writeFile } from 'fs/promises';
import { join, resolve } from 'path';
import { fileURLToPath } from 'url';

// Get the directory name in ESM
const __dirname = fileURLToPath(new URL('.', import.meta.url));

// Token reference tracking
class TokenReferenceTracker {
    constructor() {
        this.referenceMap = new Map();
    }

    addReference(token, referencedBy) {
        if (!this.referenceMap.has(token)) {
            this.referenceMap.set(token, new Set());
        }
        this.referenceMap.get(token).add(referencedBy);
    }

    getReferences(token) {
        return this.referenceMap.get(token) || new Set();
    }
}

// File Discovery and Processing
async function discoverTokenFiles() {
    const rootDir = resolve(__dirname, '..', 'json');
    try {
        const files = await readdir(rootDir);
        return files
            .filter(file => file.endsWith('.json'))
            .map(file => join(rootDir, file));
    } catch (error) {
        console.error('Error discovering token files:', error);
        return [];
    }
}

async function loadTokenFile(path) {
    try {
        const content = await readFile(path, 'utf-8');
        return {
            path,
            content: JSON.parse(content)
        };
    } catch (error) {
        console.error(`Error loading token file ${path}:`, error);
        return null;
    }
}

// Token Processing
function processTokens(tokens) {
    const flattenedTokens = new Map();
    
    function flatten(obj, path = '') {
        for (const [key, value] of Object.entries(obj)) {
            const currentPath = path ? `${path}.${key}` : key;
            
            if (isDesignToken(value)) {
                flattenedTokens.set(currentPath, value.value);
            } else {
                flatten(value, currentPath);
            }
        }
    }
    
    flatten(tokens);
    return flattenedTokens;
}

function resolveReferences(tokens, tracker) {
    const resolved = new Map();
    
    for (const [path, value] of tokens) {
        if (typeof value === 'string' && isTokenReference(value)) {
            const refPath = value.slice(1, -1); // Remove {} braces
            const resolvedValue = tokens.get(refPath);
            if (resolvedValue !== undefined) {
                resolved.set(path, resolvedValue);
                tracker.addReference(refPath, path);
            } else {
                console.warn(`Unresolved reference: ${value} in ${path}`);
                resolved.set(path, value);
            }
        } else {
            resolved.set(path, value);
        }
    }
    
    return resolved;
}

// TypeScript Generation
function generateTypeScript(tokens, tracker) {
    const output = [];
    
    // Add type definitions
    output.push('// Generated by Design Token Converter');
    output.push('// Do not edit directly');
    output.push('');
    output.push('export interface DesignToken<T> {');
    output.push('  value: T;');
    output.push('  type?: string;');
    output.push('  description?: string;');
    output.push('}');
    output.push('');
    
    // Generate token structure
    output.push('export const tokens = {');
    
    const tokenPaths = Array.from(tokens.keys()).sort();
    for (const path of tokenPaths) {
        const value = tokens.get(path);
        const pathParts = path.split('.');
        const indentation = '  '.repeat(pathParts.length);
        
        output.push(`${indentation}${formatPropertyName(pathParts.at(-1))}: {`);
        output.push(`${indentation}  value: ${JSON.stringify(value)},`);
        output.push(`${indentation}} as const,`);
    }
    
    output.push('} as const;');
    output.push('');
    
    // Generate types
    output.push('export type TokenTypes = typeof tokens;');
    
    return output.join('\n');
}

// Helper functions
function isDesignToken(value) {
    return typeof value === 'object' && value !== null && 'value' in value;
}

function isTokenReference(value) {
    return value.startsWith('{') && value.endsWith('}');
}

function formatPropertyName(name) {
    return name.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

// Main conversion function
async function convertDesignTokens() {
    try {
        // Discover all JSON files
        const files = await discoverTokenFiles();
        if (files.length === 0) {
            throw new Error('No token files found in /json directory');
        }
        
        // Load and process all token files
        const tracker = new TokenReferenceTracker();
        const allTokens = new Map();
        
        for (const file of files) {
            const tokenFile = await loadTokenFile(file);
            if (tokenFile) {
                const tokens = processTokens(tokenFile.content);
                for (const [path, value] of tokens) {
                    allTokens.set(path, value);
                }
            }
        }
        
        // Resolve references
        const resolvedTokens = resolveReferences(allTokens, tracker);
        
        // Generate TypeScript
        const typescript = generateTypeScript(resolvedTokens, tracker);
        
        // Write output
        const outputPath = resolve(__dirname, '..', 'dist', 'tokens.ts');
        await writeFile(outputPath, typescript);
        console.log('Successfully converted design tokens to TypeScript');
        
    } catch (error) {
        console.error('Error converting design tokens:', error);
        process.exit(1);
    }
}

// Run the conversion
convertDesignTokens();